name: DevOps pipeline
on: [push]
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3         # uses: an already existing action and run for linux commands
        # checkout clones the code in the environment wehre the job is going to be runs
      - uses: actions/setup-node@v3 # install node in the env (ubuntu-latest in this case)
        with:
          node-version: 14
      - run: npm install     
      - run: npm test

